# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
#hh
name: ZZU-JKSB

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "re" ]
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: JKSB
      env:
        UPW: ${{ secrets.UPW }}
        UID: ${{ secrets.UID }}
        SCKEY: ${{ secrets.SCKEY }}
      run: |
        python main.py
